# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/pmlbeta/betafabgui2/betafab2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(508, 625)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.addFromCommandLinePushButton = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.addFromCommandLinePushButton.setIcon(icon)
        self.addFromCommandLinePushButton.setObjectName("addFromCommandLinePushButton")
        self.gridLayout.addWidget(self.addFromCommandLinePushButton, 0, 1, 1, 1)
        self.commandLineLineEdit = QtWidgets.QLineEdit(Form)
        self.commandLineLineEdit.setClearButtonEnabled(True)
        self.commandLineLineEdit.setObjectName("commandLineLineEdit")
        self.gridLayout.addWidget(self.commandLineLineEdit, 0, 0, 1, 1)
        self.addFromComboBoxesPushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFromComboBoxesPushButton.sizePolicy().hasHeightForWidth())
        self.addFromComboBoxesPushButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.addFromComboBoxesPushButton.setIcon(icon)
        self.addFromComboBoxesPushButton.setObjectName("addFromComboBoxesPushButton")
        self.gridLayout.addWidget(self.addFromComboBoxesPushButton, 1, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.aminoAcidKindComboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aminoAcidKindComboBox.sizePolicy().hasHeightForWidth())
        self.aminoAcidKindComboBox.setSizePolicy(sizePolicy)
        self.aminoAcidKindComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.aminoAcidKindComboBox.setObjectName("aminoAcidKindComboBox")
        self.aminoAcidKindComboBox.addItem("")
        self.aminoAcidKindComboBox.addItem("")
        self.aminoAcidKindComboBox.addItem("")
        self.aminoAcidKindComboBox.addItem("")
        self.aminoAcidKindComboBox.addItem("")
        self.aminoAcidKindComboBox.addItem("")
        self.aminoAcidKindComboBox.addItem("")
        self.gridLayout_2.addWidget(self.aminoAcidKindComboBox, 1, 2, 1, 1)
        self.sidechain2ComboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidechain2ComboBox.sizePolicy().hasHeightForWidth())
        self.sidechain2ComboBox.setSizePolicy(sizePolicy)
        self.sidechain2ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.sidechain2ComboBox.setObjectName("sidechain2ComboBox")
        self.gridLayout_2.addWidget(self.sidechain2ComboBox, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 1)
        self.sidechain3ComboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidechain3ComboBox.sizePolicy().hasHeightForWidth())
        self.sidechain3ComboBox.setSizePolicy(sizePolicy)
        self.sidechain3ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.sidechain3ComboBox.setObjectName("sidechain3ComboBox")
        self.gridLayout_2.addWidget(self.sidechain3ComboBox, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.stereo3ComboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stereo3ComboBox.sizePolicy().hasHeightForWidth())
        self.stereo3ComboBox.setSizePolicy(sizePolicy)
        self.stereo3ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.stereo3ComboBox.setObjectName("stereo3ComboBox")
        self.stereo3ComboBox.addItem("")
        self.stereo3ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.stereo3ComboBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.stereo2ComboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stereo2ComboBox.sizePolicy().hasHeightForWidth())
        self.stereo2ComboBox.setSizePolicy(sizePolicy)
        self.stereo2ComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.stereo2ComboBox.setObjectName("stereo2ComboBox")
        self.stereo2ComboBox.addItem("")
        self.stereo2ComboBox.addItem("")
        self.gridLayout_2.addWidget(self.stereo2ComboBox, 1, 0, 1, 1)
        self.secondaryStructureComboBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.secondaryStructureComboBox.sizePolicy().hasHeightForWidth())
        self.secondaryStructureComboBox.setSizePolicy(sizePolicy)
        self.secondaryStructureComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.secondaryStructureComboBox.setObjectName("secondaryStructureComboBox")
        self.gridLayout_2.addWidget(self.secondaryStructureComboBox, 1, 5, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 5, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AcePushButton = QtWidgets.QPushButton(Form)
        self.AcePushButton.setObjectName("AcePushButton")
        self.horizontalLayout_2.addWidget(self.AcePushButton)
        self.ButPushButton = QtWidgets.QPushButton(Form)
        self.ButPushButton.setObjectName("ButPushButton")
        self.horizontalLayout_2.addWidget(self.ButPushButton)
        self.NMePushButton = QtWidgets.QPushButton(Form)
        self.NMePushButton.setObjectName("NMePushButton")
        self.horizontalLayout_2.addWidget(self.NMePushButton)
        self.VALXVALPushButton = QtWidgets.QPushButton(Form)
        self.VALXVALPushButton.setObjectName("VALXVALPushButton")
        self.horizontalLayout_2.addWidget(self.VALXVALPushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sequenceTreeView = QtWidgets.QTreeView(Form)
        self.sequenceTreeView.setAlternatingRowColors(True)
        self.sequenceTreeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.sequenceTreeView.setRootIsDecorated(False)
        self.sequenceTreeView.setUniformRowHeights(True)
        self.sequenceTreeView.setObjectName("sequenceTreeView")
        self.horizontalLayout_5.addWidget(self.sequenceTreeView)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.removeToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeToolButton.sizePolicy().hasHeightForWidth())
        self.removeToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.removeToolButton.setIcon(icon)
        self.removeToolButton.setIconSize(QtCore.QSize(24, 24))
        self.removeToolButton.setObjectName("removeToolButton")
        self.verticalLayout_2.addWidget(self.removeToolButton)
        self.clearToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearToolButton.sizePolicy().hasHeightForWidth())
        self.clearToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("edit-clear-all")
        self.clearToolButton.setIcon(icon)
        self.clearToolButton.setIconSize(QtCore.QSize(24, 24))
        self.clearToolButton.setObjectName("clearToolButton")
        self.verticalLayout_2.addWidget(self.clearToolButton)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.cutToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cutToolButton.sizePolicy().hasHeightForWidth())
        self.cutToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("edit-cut")
        self.cutToolButton.setIcon(icon)
        self.cutToolButton.setIconSize(QtCore.QSize(24, 24))
        self.cutToolButton.setObjectName("cutToolButton")
        self.verticalLayout_2.addWidget(self.cutToolButton)
        self.copyToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyToolButton.sizePolicy().hasHeightForWidth())
        self.copyToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.copyToolButton.setIcon(icon)
        self.copyToolButton.setIconSize(QtCore.QSize(24, 24))
        self.copyToolButton.setObjectName("copyToolButton")
        self.verticalLayout_2.addWidget(self.copyToolButton)
        self.pasteToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasteToolButton.sizePolicy().hasHeightForWidth())
        self.pasteToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("edit-paste")
        self.pasteToolButton.setIcon(icon)
        self.pasteToolButton.setIconSize(QtCore.QSize(24, 24))
        self.pasteToolButton.setObjectName("pasteToolButton")
        self.verticalLayout_2.addWidget(self.pasteToolButton)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.moveToTopToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveToTopToolButton.sizePolicy().hasHeightForWidth())
        self.moveToTopToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("go-top")
        self.moveToTopToolButton.setIcon(icon)
        self.moveToTopToolButton.setIconSize(QtCore.QSize(24, 24))
        self.moveToTopToolButton.setObjectName("moveToTopToolButton")
        self.verticalLayout_2.addWidget(self.moveToTopToolButton)
        self.moveUpToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveUpToolButton.sizePolicy().hasHeightForWidth())
        self.moveUpToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("go-up")
        self.moveUpToolButton.setIcon(icon)
        self.moveUpToolButton.setIconSize(QtCore.QSize(24, 24))
        self.moveUpToolButton.setObjectName("moveUpToolButton")
        self.verticalLayout_2.addWidget(self.moveUpToolButton)
        self.moveDownToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveDownToolButton.sizePolicy().hasHeightForWidth())
        self.moveDownToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("go-down")
        self.moveDownToolButton.setIcon(icon)
        self.moveDownToolButton.setIconSize(QtCore.QSize(24, 24))
        self.moveDownToolButton.setObjectName("moveDownToolButton")
        self.verticalLayout_2.addWidget(self.moveDownToolButton)
        self.moveToBottomToolButton = QtWidgets.QToolButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveToBottomToolButton.sizePolicy().hasHeightForWidth())
        self.moveToBottomToolButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("go-bottom")
        self.moveToBottomToolButton.setIcon(icon)
        self.moveToBottomToolButton.setIconSize(QtCore.QSize(24, 24))
        self.moveToBottomToolButton.setObjectName("moveToBottomToolButton")
        self.verticalLayout_2.addWidget(self.moveToBottomToolButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.targetObjectNameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.targetObjectNameLineEdit.setObjectName("targetObjectNameLineEdit")
        self.horizontalLayout_4.addWidget(self.targetObjectNameLineEdit)
        self.generatePushButton = QtWidgets.QPushButton(self.groupBox)
        icon = QtGui.QIcon.fromTheme("system-run")
        self.generatePushButton.setIcon(icon)
        self.generatePushButton.setObjectName("generatePushButton")
        self.horizontalLayout_4.addWidget(self.generatePushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.cleanupCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.cleanupCheckBox.setObjectName("cleanupCheckBox")
        self.verticalLayout_3.addWidget(self.cleanupCheckBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveg96PushButton = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.saveg96PushButton.setIcon(icon)
        self.saveg96PushButton.setObjectName("saveg96PushButton")
        self.horizontalLayout.addWidget(self.saveg96PushButton)
        self.saveCRDPushButton = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon.fromTheme("document-save-as")
        self.saveCRDPushButton.setIcon(icon)
        self.saveCRDPushButton.setObjectName("saveCRDPushButton")
        self.horizontalLayout.addWidget(self.saveCRDPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.commandLineLineEdit, self.addFromCommandLinePushButton)
        Form.setTabOrder(self.addFromCommandLinePushButton, self.stereo2ComboBox)
        Form.setTabOrder(self.stereo2ComboBox, self.stereo3ComboBox)
        Form.setTabOrder(self.stereo3ComboBox, self.aminoAcidKindComboBox)
        Form.setTabOrder(self.aminoAcidKindComboBox, self.sidechain2ComboBox)
        Form.setTabOrder(self.sidechain2ComboBox, self.sidechain3ComboBox)
        Form.setTabOrder(self.sidechain3ComboBox, self.addFromComboBoxesPushButton)
        Form.setTabOrder(self.addFromComboBoxesPushButton, self.AcePushButton)
        Form.setTabOrder(self.AcePushButton, self.NMePushButton)
        Form.setTabOrder(self.NMePushButton, self.sequenceTreeView)
        Form.setTabOrder(self.sequenceTreeView, self.removeToolButton)
        Form.setTabOrder(self.removeToolButton, self.clearToolButton)
        Form.setTabOrder(self.clearToolButton, self.moveToTopToolButton)
        Form.setTabOrder(self.moveToTopToolButton, self.moveUpToolButton)
        Form.setTabOrder(self.moveUpToolButton, self.moveDownToolButton)
        Form.setTabOrder(self.moveDownToolButton, self.moveToBottomToolButton)
        Form.setTabOrder(self.moveToBottomToolButton, self.targetObjectNameLineEdit)
        Form.setTabOrder(self.targetObjectNameLineEdit, self.generatePushButton)
        Form.setTabOrder(self.generatePushButton, self.saveg96PushButton)
        Form.setTabOrder(self.saveg96PushButton, self.saveCRDPushButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Beta-peptide builder"))
        self.addFromCommandLinePushButton.setToolTip(_translate("Form", "Append the peptides designated in the command-line to the list"))
        self.addFromCommandLinePushButton.setText(_translate("Form", "Add"))
        self.commandLineLineEdit.setToolTip(_translate("Form", "<html><head/><body><p>Add beta-amino acids from this command line, following these rules:</p>\n"
"<dl>\n"
"<dt>&beta;<sup>2</sup>-amino acids:</dt>\n"
"<dd>([RS])B2h&lt;sc&gt;; e.g. (R)B2hV</dd>\n"
"\n"
"<dt>&beta;<sup>3</sup>-amino acids:</dt>\n"
"<dd>([RS])B3h&lt;sc&gt;; e.g. (S)B3hA</dd>\n"
"\n"
"<dt>&beta;<sup>2,3</sup>-amino acids:</dt>\n"
"<dd>(2[RS]3[RS])B23h(2&lt;sc&gt;3&lt;sc&gt;); e.g. (2S3R)B23hQR</dd>\n"
"\n"
"<dt>Bare &beta;-backbone (homo-glycine):</dt>\n"
"<dd>BA</dd>\n"
"\n"
"<dt>&alpha;-amino acids:</dt>\n"
"<dd>([RS])A&lt;sc&gt;; e.g. (S)AC </dd>\n"
"\n"
"<dt>Others:</dt>\n"
"<dd><dl>\n"
"<dt>ACE:</dt><dd>N-terminal acetyl group (must be the first residue)</dd>\n"
"<dt>NME:</dt><dd>C-terminal N-methylamide group (must be the last residue)</dd>\n"
"</dl></dd>\n"
"\n"
"\n"
"</dl><p>\n"
"A comma-separated list of more than one entries is also accepted.\n"
"<br/></p></body></html>"))
        self.commandLineLineEdit.setPlaceholderText(_translate("Form", "By hand input..."))
        self.addFromComboBoxesPushButton.setText(_translate("Form", "Add"))
        self.aminoAcidKindComboBox.setToolTip(_translate("Form", "Amino acid type"))
        self.aminoAcidKindComboBox.setItemText(0, _translate("Form", "α"))
        self.aminoAcidKindComboBox.setItemText(1, _translate("Form", "βA"))
        self.aminoAcidKindComboBox.setItemText(2, _translate("Form", "β²"))
        self.aminoAcidKindComboBox.setItemText(3, _translate("Form", "β³"))
        self.aminoAcidKindComboBox.setItemText(4, _translate("Form", "β²³"))
        self.aminoAcidKindComboBox.setItemText(5, _translate("Form", "ACPC"))
        self.aminoAcidKindComboBox.setItemText(6, _translate("Form", "ACHC"))
        self.sidechain2ComboBox.setToolTip(_translate("Form", "Sidechain on the α-carbon"))
        self.label_3.setText(_translate("Form", "β R/S"))
        self.label_5.setText(_translate("Form", "α side-chain"))
        self.label_6.setText(_translate("Form", "β side-chain"))
        self.sidechain3ComboBox.setToolTip(_translate("Form", "Sidechain on the β-carbon"))
        self.label_4.setText(_translate("Form", "Aa. type"))
        self.stereo3ComboBox.setToolTip(_translate("Form", "Absolute conformation of the sidechain on the β-carbon"))
        self.stereo3ComboBox.setItemText(0, _translate("Form", "R"))
        self.stereo3ComboBox.setItemText(1, _translate("Form", "S"))
        self.label_2.setText(_translate("Form", "α R/S"))
        self.stereo2ComboBox.setToolTip(_translate("Form", "Absolute conformation of the sidechain on the α-carbon"))
        self.stereo2ComboBox.setItemText(0, _translate("Form", "R"))
        self.stereo2ComboBox.setItemText(1, _translate("Form", "S"))
        self.label_7.setText(_translate("Form", "Sec. struct."))
        self.AcePushButton.setToolTip(_translate("Form", "Add an N-terminal acetyl group"))
        self.AcePushButton.setText(_translate("Form", "Ace"))
        self.ButPushButton.setToolTip(_translate("Form", "Add an N-terminal butyl group"))
        self.ButPushButton.setText(_translate("Form", "But"))
        self.NMePushButton.setToolTip(_translate("Form", "Add a C-terminal N-methylamide group"))
        self.NMePushButton.setText(_translate("Form", "NMe"))
        self.VALXVALPushButton.setToolTip(_translate("Form", "Add a VALXVAL heptapeptide (mainly for testing purposes)"))
        self.VALXVALPushButton.setText(_translate("Form", "VALXVAL"))
        self.removeToolButton.setToolTip(_translate("Form", "Remove the selected residue(s)"))
        self.removeToolButton.setText(_translate("Form", "Remove"))
        self.clearToolButton.setToolTip(_translate("Form", "Remove all residues"))
        self.clearToolButton.setText(_translate("Form", "Clear"))
        self.cutToolButton.setText(_translate("Form", "Cut"))
        self.copyToolButton.setText(_translate("Form", "Copy"))
        self.pasteToolButton.setText(_translate("Form", "Paste"))
        self.moveToTopToolButton.setToolTip(_translate("Form", "Move the selected residue to the top"))
        self.moveToTopToolButton.setText(_translate("Form", "Move to top"))
        self.moveUpToolButton.setToolTip(_translate("Form", "Move the selected residue up"))
        self.moveUpToolButton.setText(_translate("Form", "Move up"))
        self.moveDownToolButton.setToolTip(_translate("Form", "Move the selected residue down"))
        self.moveDownToolButton.setText(_translate("Form", "Move down"))
        self.moveToBottomToolButton.setToolTip(_translate("Form", "Move the selected residue to the bottom"))
        self.moveToBottomToolButton.setText(_translate("Form", "Move to bottom"))
        self.groupBox.setTitle(_translate("Form", "Output"))
        self.label.setText(_translate("Form", "Target object:"))
        self.targetObjectNameLineEdit.setToolTip(_translate("Form", "The name PyMOL will use for the freshly built peptide"))
        self.targetObjectNameLineEdit.setPlaceholderText(_translate("Form", "PyMOL model name (will be overwritten)..."))
        self.generatePushButton.setToolTip(_translate("Form", "Build the peptide"))
        self.generatePushButton.setText(_translate("Form", "Build..."))
        self.cleanupCheckBox.setToolTip(_translate("Form", "If selected, the built structure will be optimized using the \"clean\" command if freemol is installed, or \"sculpt\" if it is not present. Backbone atoms will be position restrained during the minimization."))
        self.cleanupCheckBox.setText(_translate("Form", "Try to clean up steric clashes"))
        self.saveg96PushButton.setToolTip(_translate("Form", "Save the peptide to a GROMOS96 coordinate file"))
        self.saveg96PushButton.setText(_translate("Form", "G96"))
        self.saveCRDPushButton.setToolTip(_translate("Form", "Save the peptide to an expanded CHARMM coordinate card file"))
        self.saveCRDPushButton.setText(_translate("Form", "CRD"))

from . import icons_rc
